# Generated by Django 4.2 on 2023-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('medical_licence_number', models.CharField(max_length=25)),
                ('education', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
                ('work_experience', models.IntegerField()),
                ('doctor_login_id', models.IntegerField()),
            ],
        ),
    ]
